name: CI
on:
  push:
    branches: [ develop ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:    
    - name: Deploy source code on cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          git pull origin develop
          docker-compose -f docker-compose-prd.yml exec -T api bash deploy_workflow_migrations.sh
          docker-compose -f docker-compose-prd.yml exec -T api python manage.py collectstatic --noinput
          docker-compose -f docker-compose-prd.yml stop
          docker-compose -f docker-compose-prd.yml up -d
